//
//  Constants.swift
//  MusicApp2
//
//  Created by Consultant on 6/10/22.
//

import Foundation

struct Desc {
    static let poloG = "Taurus Tremani Bartlett (born January 6, 1999), known professionally as Polo G, is an American rapper. He rose to prominence with his singles Finer Things and Pop Out (featuring Lil Tjay). His debut album Die a Legend (2019) peaked at number six on the US Billboard 200 and was certified platinum by the RIAA.[2] Bartlett's second studio album, The Goat (2020), peaked at number two on the Billboard 200[3] and charted ten singles on the Billboard Hot 100 chart.[4] His mainstream success continued with his third studio album Hall of Fame (2021), which became Bartlett's first chart topping album and included his first number-one single Rapstar"
    static let beyonce = "Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ bee-YON-say; née Knowles; born September 4, 1981)[4] is an American singer, songwriter, and actress. Beyoncé performed in various singing and dancing competitions as a child. She rose to fame in the late 1990s as the lead singer of Destiny's Child, one of the best-selling girl groups of all time. Their hiatus saw the release of her debut album Dangerously in Love (2003), which featured the US Billboard Hot 100 number-one singles Crazy in Love and Baby Boy.Following the 2006 disbanding of Destiny's Child, she released her second solo album, B'Day, which contained singles Irreplaceable and Beautiful Liar. Beyoncé also starred in multiple films such as The Pink Panther (2006), Dreamgirls (2006), Obsessed (2009), and The Lion King (2019). "
    static let jayZ = "Shawn Corey Carter (born December 4, 1969), known professionally as Jay-Z,[a] is an American rapper, record executive, and media proprietor. He is one of the most influential hip-hop artists in history.[7] He was the CEO of Def Jam Recordings and he has been central to the creative and commercial success of artists including Kanye West, Rihanna, and J. Cole.[8][9]Born and raised in New York City, Jay-Z first began his musical career in the late 1980s; he co-founded the record label Roc-A-Fella Records in 1995 and released his debut studio album Reasonable Doubt in 1996."
    static let bigge = "Christopher George Latore Wallace (May 21, 1972 – March 9, 1997), better known by his stage names the Notorious B.I.G., Biggie Smalls, or simply Biggie,[3] was an American rapper and songwriter. Rooted in the New York rap scene and gangsta rap traditions, he is widely considered one of the greatest rappers of all time. Wallace became known for his distinctive laid-back lyrical delivery, offsetting the lyrics' often grim content. His music was often semi-autobiographical, telling of hardship and criminality, but also of debauchery and celebration.[4] Born and raised in Brooklyn, New York City, Wallace signed to Sean Puffy Combs' label Bad Boy Records as it launched in 1993, and gained exposure through features on several other artists' singles that year. His debut album Ready to Die (1994) was met with widespread critical acclaim, and included his signature songs Juicy and Big Poppa."
    static let tupac = "Tupac Amaru Shakur (/ˈtuːpɑːk ʃəˈkʊər/ TOO-pahk shə-KOOR; born Lesane Parish Crooks, June 16, 1971 – September 13, 1996), known professionally as 2Pac and later Makaveli, was an American rapper and actor. He is widely considered one of the most influential rappers of all time.[1][2] Shakur is among the best-selling music artists, having sold more than 75 million records worldwide. Much of Shakur's music has been noted for addressing contemporary social issues that plagued inner cities, and he is considered a symbol of activism against inequality. Shakur was born in New York City to parents who were both political activists and Black Panther Party members. Raised by his mother, he relocated to Baltimore in 1984 and to the San Francisco Bay Area in 1988. With the release of his debut album 2Pacalypse Now in 1991, he became a central figure in West Coast hip hop for his conscious rap lyrics."
    static let gucci = "Radric Delantic Davis (born February 12, 1980),[2][3] known professionally as Gucci Mane, is an American rapper and record executive. He helped pioneer the hip hop subgenre of trap music alongside fellow Atlanta-based rappers T.I. and Young Jeezy, particularly in the 2000s and 2010s.[4] In 2005, Gucci Mane debuted with Trap House, followed by his second album, Hard to Kill in 2006. His third studio album Back to the Trap House was released in 2007. Following a string of critically and commercially successful mixtape releases in 2009, Gucci Mane released his fourth studio album, The State vs. Radric Davis, his first gold-certified album. Following time spent in prison between 2014 and 2016, he re-emerged with several new retail projects, including Everybody Looking (2016), which was released to critical praise."
}
